### ISSUE TITLE
Add a Readme

### ISSUE THREAD

**Issue by rahul799** [The-Codesis/codesis-website#1]
Anyone who is new to web dev or git can add a Readme file to it. You can ping me in the slack for any help.

**Comment by und3fined-v01d** [comment]
Let us have the students submit a proposal for this. This will make them accustomed to most Summer of Codes format

**Comment by rahul799** [comment]
Excellent idea.

**Comment by rahulii** [comment]
I would like to tackle the issue.Please assign it to me @rahul799.

**Comment by rahul799** [comment]
You can start working on it

**Comment by und3fined-v01d** [comment]
@rahulii feel free to create a PR. Please make small patches so that it helps us mentors review it better

**Comment by rahulii** [comment]
@rahul799 can you describe in detail what all i should add in readme?

**Comment by und3fined-v01d** [comment]
@rahulii just mention the set up steps that a person would perform to get it running on their local.

**Comment by rahulii** [comment]
@und3fined-v01d okay,so should it have similar template to README file in previous repo? It will list all the git commands needed to setup?

**Comment by und3fined-v01d** [comment]
For example if you are using a React application, write all scripts you would run from cloning the repo to getting the application up and running locally, along with system requirements, Node version etc
