### ISSUE TITLE
Update and restructurize Readme 

### ISSUE THREAD

**Issue by CapTen101** [The-Codesis/codesis-website#10]
Currently [Readme](https://github.com/The-Codesis/codesis-website/blob/master/README.md) isn't in the state one expects to. It should contains steps for setting up the repo through `git` as well as `yarn` installation. License mention can also be put up.

All tasks:
- [ ] Mention License
- [ ] Add `git` setup procedure
- [ ] Add yarn setup and Local Deployment steps

**Comment by NidhiKJha** [comment]
Hi, Thanks for opening the issue but issue #1 is similar to this one. So, I am closing it for now. Thanks :)
