### ISSUE TITLE
Add a Contact Us section

### ISSUE THREAD

**Issue by vidhi-mody** [The-Codesis/codesis-website#18]
The contact section should include links to:
- LinkedIn
- Discord
- GitHub

**Comment by Kushagraw12** [comment]
Can i take this up?

**Comment by vidhi-mody** [comment]
Sure!

**Comment by jradha11** [comment]
Can I also try working on it?

**Comment by vidhi-mody** [comment]
@jradha11 yes you can!

**Comment by jradha11** [comment]
@vidhi-mody Kindly review PR #19.

**Comment by vidhi-mody** [comment]
@jradha11 please check the feedback Nidhi has left!
