### ISSUE TITLE
Modify button name

### ISSUE THREAD

**Issue by agarwalrounak** [The-Codesis/codesis-website#6]
The button to switch between light and dark themes is currently named `Dark` in dark mode and `Light` in light mode. It should be named just the opposite, so that when a user clicks on the button named `Dark`, the website switches to the dark theme and the button name changes to `Light`.

**Comment by rahulii** [comment]
@agarwalrounak i would like to takle the issue.Can you please assign it to me?

**Comment by adiaholic** [comment]
@rahulii You can work on an issue even without being assigned explicitly.
In the PR just mention this issue number and it would just look fine ;)
